name: dog_collar_app
description: Hundehalsband BLE Control App - Vibration & Localization
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # BLE Communication - AKTUALISIERTE VERSION
  flutter_blue_plus: ^1.33.17
  
  # Permissions - AKTUALISIERTE VERSION  
  permission_handler: ^12.0.0+1
  
  # State Management
  provider: ^6.1.2
  
  # UI Components  
  cupertino_icons: ^1.0.8
  
  # Math & Utilities
  vector_math: ^2.1.4
  
  # Storage
  shared_preferences: ^2.5.3
  
  # Formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Assets auskommentiert da Ordner nicht existieren
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Fonts auskommentiert da Dateien nicht existieren  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700